# References:

FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y python3-pip 

RUN pip3 install paho-mqtt
RUN pip3 install ibm-cos-sdk

WORKDIR /
COPY image_saver.py /
